#----------------------------------------------------------------------
# This file was generated by generate_icon.py
# It contains base64-encoded PNG icons for use with PySide6
#

import base64
from PySide6.QtGui import QPixmap, QIcon
from PySide6.QtCore import QByteArray


def get_icon_from_base64(data_str):
    """Convert base64 string to QIcon"""
    try:
        byte_array = QByteArray.fromBase64(data_str.encode('ascii'))
        pixmap = QPixmap()
        pixmap.loadFromData(byte_array)
        return QIcon(pixmap)
    except Exception as e:
        print(f"Error loading icon: {e}")
        return QIcon()


# Icon catalog - maps icon names to base64-encoded PNG data
ICON_DATA = {
    'bug_report_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABRUlEQVRIS+VUzUrDQBCe3cYaRJoe' \
    'RNMcpG8n6FGD4AuUmrOCTydFbPSgmIqYGJJx02Zr3OzugCWImFOS3ZnvZ3Y/Bh0/rOP+8LsANwBb' \
    'i8B7C+dJX6c0Gnn5IE52jgBykxNWBVHgZQCsD4hFGCdOs0kUDHH1jZkg4P4IoCoSLEtgzEAEc5M6' \
    'CUjOYK1CSxE/BMC27aDYLRIeC/ZLaxim47M4nVXvE384djjc1hZZVbQAvryteSGi8J8bhtyyL5y/' \
    'fOtJAvA0Ozx9fr/TAUx8VyhxayWrHSSAbCSVyAJVmfpfbUwOuTMAE1PTSaH2kzMwSVetlN//cAY5' \
    'K/Yu7l+ftPfgYHcfes5jc420qPOLpk9MW1S0L1ezBxl2lyOvEGGqjQpdjKtWkgBVwdQfHHPOr5rF' \
    'ZVmenD8srm1JugxJasOm638f4BMyJbYZ2oGC7gAAAABJRU5ErkJggg==',
    'bug_report_48dp_8b1a10_fill0_wght400_grad0_opsz48': 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAEXElEQVRoQ+1YTWzUVhCe500IZMna' \
    'CEKyRlWlFokfIUQOgECCW6tWPUDpqRK99ILUa7OBcsFC4ke7CzcuXDjwc+JXQpUKV9RKrVQQHPoj' \
    'cWjV7qYJoTbLJtDNehjvrldvnY2fn59XKFV8sz3zzffNzJv3bAZL/GJLnD8sC3jbFVyuwJKvQCGr' \
    'z1fLzqAF8J+smLxpVGdr9og1DS9lfX17pRbKm/prBmyFB1Yt2QMyIgpZ4wWNkKGGb80eiitCSUDB' \
    '1OcA2Eo/G1FF8OTfqgAvuNcGlIXBqCKIvEOZz7TtFbLvYShVwCfhrQNgLOXfYw3GoA/P0LP9gLiC' \
    'gjxkiCdcTbsuIzbKukhEgBcomFlRcJW+57ETEVAwjYcEukNEmn+PgDMTJWeYnqGMX9BWSQBNHS1t' \
    'GvUuBOYQ3dPI8DFj4IKrbadp9Q017OqgbRXqw1ap8iyuCCUBlPnO7CF+lys7H4WRIZ/b9P4Ab0PT' \
    'K0XJcOOIiC2Aev4JZXRbO+h8fW9uqvJDFBKF9UN7oC/1PWdr50r2mii+0i20IMtdojDX3TU++eIn' \
    'GQLF0cxO1LQfRT4kLDTJwgoIBSBcyZXtL0REur2nKl6mKh4O8+25AFEAkTBRgkT4wgoECRRGM5+A' \
    'pt1tPsdfcyVni4hk+KLWf6H9dHPL5iARviODJy8gq9+kHfbTRhAXvsxN2pf4gK09YVEORHCMf5k3' \
    'M58z0K418wEPqB339VRAPqs/ZYy914jHYGzib/tRQEDoxhRsifwGYwdD8DZC7/qT3r/bUwH8SRJr' \
    'tezEdHVSScBwepT195dbGM9JwNqeCiiaRoVS3NhR3Vev3zn6fO6vjpagjIYRCFbMMofWpSE13fTB' \
    'GVpT6xIVYBmGwQOmB6FE96sWEyAT3LMNCqjOso08hmXbdhimcBGHjbluLSQrIN/ZQgvclcfo/0HA' \
    'v4G0tFuq2xqQrUBnCzWO1g6PITojCVsoSIivSOIthDhFp9kRmSQkLkD2aMCvAUo/feTYyU6hLhWY' \
    '9acQzuPGiSnnqco+cH7tqg31gYHWKMZnNEa9r7TIV4wKcGcXhEO09d9SEXB2NPNxStO+be0Dv5OA' \
    'TZHZk6G0ADpKnKKjxPHmvgM3ScBnMgEXVDRr3CAWh5pwcJJa6IQMnlCAbE/LBPdsVfGVBTDAD8dL' \
    'zn1Z4p590dQ/QGD3wnx7upH5gUVBFiMoyr7nJ8IWViBacKzR4mv85I16Efn2NItCdDHc2ALOmcYY' \
    '/Qf5mQeuzsIa0eHLGobV6X6jwvvRb8cj42XnYlTxHb5xnHwf+r1epB9WX3dgIPzBWP3weKnygH9e' \
    'GMnshhS7SoPvff45TZ5HNHk6vtJkOMWugB+kaGa+QtAuyARt2yr80fAxlAV4QBZA32BW/83/1BSL' \
    'wRmo17fm/nk5JbYNt0hEAB+C2uoYgZImNtDRKojzdJ/Xy451BKCmSjzRCiRFJg5O4hWIQ0LFZ1mA' \
    'SvaS8F2uQBJZVMF4A+zCzkBHibvnAAAAAElFTkSuQmCC',
    'globe_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACTElEQVRIS72VP2/TQBjG73wOSCGx' \
    'IwFJnAlRqalCBxBIlIoBvgASolthQHwDwI66MRXqJF8BIdG5EgsrE38F6oBQC0V0i0vbIbFpkRr7' \
    'Xs6Bs2z3bDeVSqYk9/r9Pc9zr+8wOuIPPuL+KBPQOZ2/4Mm5JYzxmbAYAPjhuYOZua3d5TSRiYCF' \
    'U8W6dIysHsQhDOi4sWWviWqFAFNTnmMs3fYfAEC7APR6c8P+wBuYZXUMy/h7xBGlz4wN+24csg9g' \
    'aqofx02/EANcemj1P8UfatVKIHQGsKRb/VvhtQigXS00QJK/+AWk28vfR+g3L+5UlClKpLdZkdE9' \
    'b6K57XzldREAVwaud9XYdF6HmyWqFhD1bi/oG3xpa+pFwPgjAuToVk85cCwCgMuinfsXbQBoaeoq' \
    'wriOXG9a33T2RTGKAzbCK4bVbwz3kQvgDcL20vLOAvI+/x+QqBpgnY3g2cBxuXgFyeRNZCSpe45P' \
    'YaKDrDHMijAedRARe8HW4+eNCOafQWwDx0RrrWrhGpLkV4Bgzej2xyOb3CkXp6lMIrOf5CbJhVkr' \
    '7TDFeeTRKf2n/T4C8H9kTQYHigBcvV8jfNGGgEphEhH5s0h5WvaPaih/ApV2/OcouI2m9WtFeFT4' \
    'f7aryguQpBtxSBJgvqJczhHp3bA+67DjTU2ttIgxmg1D4oAnbM+ITF6yGvVvc7qoW/aduLDEC2f+' \
    'ZHEid5wEVtPGV9rz6g+2nW+imswr8zG7Momce8pG+HykAcCy6w7uHfrKTFM8ylqmg1GaiWr/ADAy' \
    '7hmHTL+9AAAAAElFTkSuQmCC',
    'info_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACeElEQVRIS91Vv2/TQBS+8zmUhiSO' \
    'BCRxxMCUVhEDqPxo6QJsLEgINmBA/Ae0Seg/0IDd8CcgJDpXYmEDFkD8KHRAqJRKsMUprUTslABN' \
    '7h5nOw6x4zhJpS548vk+v+973733DqM9fvAex0d9CUqHwyeoGFrCGB/tFAMAX2mzcXVus74SJLIn' \
    'wb1D0TFhH/k8SIbQYJn8prHuh/UlUOTYI4yF6+YPAKgOwM4XKsbbzgClZGySEeEZ/zZq4Rh7mK8Y' \
    'N70kXQSKLJl2XDaBGODkrKa/D8pCTUSnkEheWRiApZymX+nEuwgWUpEsCOInE0DK1fBthH4NYtH9' \
    'I2iUsnjdxLIdOl7Yqq05/7kI1HQcLBBlU4UN47U3uJqW/pjfcmV9xLunJKLTWCQv7P1qO277pShL' \
    'EyLGywiQkdOqkp9yTvC7RbDfd1+Ob/O6PAAIJvJl/YNlswNUZWkNYZwRuPoZH/WDWKUmpQuI4Ke8' \
    'hFfzmp51E7Ts6UxvkKDdNto2O3H+ZTAAgXNGQSK8mP+IgDfYN3Pe0CadvvO9ZjeO5+lnkZqKnEOC' \
    '+JxX0TqvoozrkEuJ6Fkmkpd8NNTyWjW2GwIlHf/JPQ8jyiZzG8YbF4G5aDcawKmCpi8Pk0GRqxe5' \
    '+p6NZhEkI8cQET+a70ONCj7waLo1KqCZLWjbq464rmG3kIo9BkG4ZKXH2OnZivEuqB/mk7EzISLY' \
    'Y6XfsHMCKXJ8EWN0zV7DD0ThouOpg7nLz4yI5Alf22MF2GJOM254xfS8cOYPRsdDI6SdalAWwg4d' \
    'm9mqffHD9L0yi/zKJGLoAS/h464AACvNZuPWrq/MIMXD7PXNYJhgfti/s3UYKJqhuqkAAAAASUVO' \
    'RK5CYII=',
    'logout_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAvklEQVRIS2NkoDFgpLH5DPS1oFec' \
    'z+IfM9NxfL4qffaBJEehKO6WEvhPKMioYgGphuBzFFYfDBoLuiT5ChkZmfiADmrE5QuyfdAgwCDA' \
    'zSXwHmpwAy5LyLYAZHCXCJcRIxvbWXyWUGQByOAeCT7T/0xMp3BZQpQFxCRfpDhACa7BYQG+dE6V' \
    'IMJlAU0juUOQgZ+ZU+ADbZMpLTMaoUIRJk9UKiLWMGzq6Fxci/FaMrAwH6NZhUNJUBBVmg5JCwDk' \
    'e3sZvHmHQgAAAABJRU5ErkJggg==',
    'settings_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACqElEQVRIS71VTWsTURS9b8baUG1e' \
    'oEqS+RVFaUFXlgq6ciP4sdKVKH6gyKQVrKbWRTMJKFhFl7pRwY1LMdWlmID5F5NUUsjEVg1m3vPM' \
    'NJPm48UUkjqbZGbuPefec+67w2iXL7bL+LQjgrQRkapCTLvSN79vgAc8VIKkQWNJm362VhwQBBV3' \
    '3gexqtyuDtIG/03ERolkNmc7J6fj/CsxdtgD6SSQUn7LF53pKYN/YMRmkVMzbSfUWlwbQSrKZzWd' \
    'ZZXGS5k3AeZLFuc5kE6p4oQrj8+tOavBuzaCoHWt/mfS1fULjGm3JMn1hO0cUIGh2zK6nZBSPKK6' \
    '+4qNjBRaO/X+NwmsGH/GNHaFJG2axcp+FaAV55cgy55fperzJJHojLGMyCYAx6Sgp4lS5VobAaqv' \
    '4AH3k6S8DDleBADpGD9DGnvbBijEPbNUXWrGRMPnSNdeN+4d+BVpI2iM4xP8+swg2da8xzkYtSuh' \
    'G0Q1ePIZnhxrgK8A/LrSA++hFQ/fhfZLUkgrUXLmIMtpxtg7pfEkFk27moQXFtQ24cVColh92Brb' \
    'Paax8AJp2gO0kMHImano+ClN198rCYRIQqZFy+AZjOltDMQdDMRyTwKYtALGq75CJD8hGLPd+yQH' \
    'EoEgu3UO/LwM8swuiVpNdl1xfn6t+iYIsqL8LNNZ894HEuJ+olRFp1vXMkzWmybLdXTvj/ZQxzQd' \
    'j2wAcR8JmTJLznwbQasULg6arusXiWk3UWsZ1RxUeQBpypBmAu08lnX35T8PmgfQZ1UUcDYO+YXE' \
    'eQFjOak0vu4eNb//+NLlQVNvg9dQ1V6YtZq3nRNYdt7e8YE7l513VnJF5wiW3UfkzMDhDWyB8Z5T' \
    '5L0YaF0ThZJE2Mbb1///4Kh0HeoXTWncAA93JNEA+PQXOdBGKHRfn9kAAAAASUVORK5CYII=',
    'update_24dp_8b1a10_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACHUlEQVRIS8VVT2vUUBCfSdquq3az' \
    'YGmbeBGhNyketofePCmIZ6EXC36Bekmqt4IF6eZQv4FQb3rqobSo4M1DRUrvXgSbRFow2bLtttt9' \
    '42zqK5uQvKxI2VyWTWbm9+fNzEO45AcvuT4MHmB1wrh9puE6U7mTUEv0qYlibsk7PFC5kKvgHYD+' \
    'wzKOAXBYaSNB0/bDUY4h16pSN9b2wou6mQDLN8o3S6XST1lYCHi6GIRveoFcs/IMUFuV79qHnbHh' \
    'UT1WowRYAtCuWdXO38QNDn6kUlA3jR1EvNsbowRgmUccXCaiD44fPUiwzrCg+71uVXfZimkZmwvg' \
    'TlwfB33oV1qmTEx7LP+nFeYDmMY2IM4IEk8W/cbbdOL/A+RYkKegnyFNdFFWm/VzBn3PQTFAPBdX' \
    'uOVPbC/i3+LnnxR0y7mW0WKQUhZI4aBxT3/lnq6REPNO0FjL4ydBCOjU8SIG41adNBzUcAWIvtl+' \
    'VJO5SQUFbdoLWLeMExS0bAeNl+fKztfEWVtMvdhvfM8EiAPNasSLrcJMNpnJw2KXY9u+sG2zbFuL' \
    'z6bcm5O5iyQbnuaPPM33VSCuaXzm2bnXjdn2wqH3AHLNxGmZACtjVy1tZGTvorAgxw4iN2GRWVlA' \
    '1F7Ld9Rum85+M0iTUV44ci+pFBDB0S0/rDxOMc89g3SxV3zh6DpsIeBU4hufUacVzT3/DZGKwOCv' \
    'zH66aKAK/gC+KugZDl+tkQAAAABJRU5ErkJggg==',
}


def get_icon(name):
    """Get QIcon by name from the catalog"""
    name = name.lower()
    if name in ICON_DATA:
        return get_icon_from_base64(ICON_DATA[name])
    print(f"Warning: Icon '{name}' not found in catalog")
    return QIcon()

